name: dotnet-dependency
on:
  pull_request:
    branches: ["main"]

jobs:
  dependency-review:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4

      - name: 'Restore Dependencies'
        run: dotnet restore

      - name: 'Run Dependency Review'
        uses: actions/dependency-review-action@v3


